apiVersion: v1
kind: Service
metadata:
  name: {{ include "harness-doom.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "harness-doom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      nodePort: {{ .Values.service.gateNodePort }}
      protocol: TCP
      name: gate
  selector:
    {{- include "harness-doom.selectorLabels" . | nindent 4 }}
