replicaCount: 1

image:
  repository: doom-wasm
  tag: latest
  pullPolicy: IfNotPresent

gateServer:
  image:
    repository: doom-gate-server
    tag: latest
    pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30666
  gateNodePort: 30667

resources:
  game:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi
  gateServer:
    limits:
      cpu: 50m
      memory: 32Mi
    requests:
      cpu: 25m
      memory: 16Mi

namespace: doom

harness:
  apiKey: ""
  accountId: ""
  orgId: ""
  projectId: ""
  pipelineId: "doom_booth_deploy"
  baseUrl: "https://app.harness.io"
